/**
 * The file contents for the shared environment configuration across all environments.
 * All environment will extends to this common configuration.
 *
 * However configuration defined in the environment files will override this common configuration.
 */

module.exports = {
  /**
   * Defines the app version that is deployed on particular environment.
   * In general this will be app version generated by CI-CD pipelines as part of deployment.
   */
  buildVersion: process.env.BUILD_VERSION || 'alfaSquare'
};
